# Generated by Django 5.1.4 on 2025-08-28 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_hash",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField()),
                ("last_url", models.URLField(max_length=500)),
                ("visit_count", models.PositiveIntegerField(default=1)),
                ("first_visit", models.DateTimeField(auto_now_add=True)),
                ("last_visit", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_visit"],
                "indexes": [
                    models.Index(
                        fields=["session_hash"], name="system_user_session_17349b_idx"
                    ),
                    models.Index(
                        fields=["user", "-last_visit"],
                        name="system_user_user_id_65e603_idx",
                    ),
                    models.Index(
                        fields=["-last_visit"], name="system_user_last_vi_921471_idx"
                    ),
                ],
            },
        ),
    ]
