# Generated by Django 5.2.6 on 2025-10-03 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="useractivity",
            options={
                "ordering": ["-last_visit"],
                "verbose_name": "User Activity",
                "verbose_name_plural": "User Activities",
            },
        ),
    ]
