# Generated by Django 5.2.6 on 2025-10-05 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0002_alter_useractivity_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=500)),
                ("full_path", models.CharField(max_length=500)),
                ("view_name", models.CharField(max_length=100)),
                ("http_method", models.CharField(max_length=10)),
                ("url_kwargs", models.JSONField(blank=True, default=dict)),
                ("query_params", models.JSONField(blank=True, default=dict)),
                ("referer", models.URLField(blank=True, max_length=500, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "Activity Log",
                "verbose_name_plural": "Activity Logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AlterModelOptions(
            name="useractivity",
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "User Activity",
                "verbose_name_plural": "User Activities",
            },
        ),
        migrations.RemoveIndex(
            model_name="useractivity",
            name="system_user_user_id_65e603_idx",
        ),
        migrations.RemoveIndex(
            model_name="useractivity",
            name="system_user_last_vi_921471_idx",
        ),
        migrations.RenameField(
            model_name="useractivity",
            old_name="first_visit",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="useractivity",
            old_name="last_visit",
            new_name="updated_at",
        ),
        migrations.RemoveField(
            model_name="useractivity",
            name="last_url",
        ),
        migrations.RemoveField(
            model_name="useractivity",
            name="visit_count",
        ),
        migrations.AddIndex(
            model_name="useractivity",
            index=models.Index(
                fields=["user", "-updated_at"], name="system_user_user_id_4da49a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useractivity",
            index=models.Index(
                fields=["-updated_at"], name="system_user_updated_811c92_idx"
            ),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="system.useractivity",
            ),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["activity", "-timestamp"], name="system_acti_activit_ac1bc4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["view_name", "-timestamp"],
                name="system_acti_view_na_28b5e4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["-timestamp"], name="system_acti_timesta_53754e_idx"
            ),
        ),
    ]
