# Generated by Django 5.2.6 on 2025-09-28 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lecture", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LectureMarker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.FloatField(help_text="Marker timestamp in seconds"),
                ),
                ("text", models.TextField(help_text="Marker note text")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lecture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="markers",
                        to="lecture.lecture",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lecture_markers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["lecture", "timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "lecture"],
                        name="lecture_lec_user_id_3b4812_idx",
                    ),
                    models.Index(
                        fields=["lecture", "timestamp"],
                        name="lecture_lec_lecture_1cd2bc_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="lecture_lec_user_id_8c1b6e_idx",
                    ),
                ],
            },
        ),
    ]
