# Generated by Django 5.1.4 on 2025-08-28 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lecture", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecture",
            name="file_hash",
            field=models.CharField(
                blank=True,
                help_text="SHA256 hash of original filename for duplicate detection",
                max_length=64,
            ),
        ),
        migrations.AddIndex(
            model_name="lecture",
            index=models.Index(
                fields=["topic", "file_hash"], name="lecture_lec_topic_i_81aec5_idx"
            ),
        ),
    ]
