# Generated by Django 5.1.4 on 2025-08-26 17:17

import apps.lecture.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lecture", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lecture",
            name="audio_file",
            field=models.FileField(upload_to=apps.lecture.models.lecture_upload_path),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="file_size",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
