# Generated by Django 5.1.4 on 2025-08-27 08:54

import apps.lecture.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lecture", "0002_alter_lecture_audio_file_alter_lecture_file_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="cover",
            field=models.ImageField(
                blank=True, null=True, upload_to=apps.lecture.models.course_cover_path
            ),
        ),
        migrations.AlterField(
            model_name="lecturer",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to=apps.lecture.models.lecturer_photo_path
            ),
        ),
    ]
