# Generated by Django 5.1.4 on 2025-08-29 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lecture", "0002_lecture_file_hash_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LectureProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_time",
                    models.FloatField(
                        default=0.0, help_text="Current playback position in seconds"
                    ),
                ),
                (
                    "completed",
                    models.BooleanField(
                        default=False, help_text="Whether lecture was fully listened to"
                    ),
                ),
                (
                    "listen_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of times this lecture was played"
                    ),
                ),
                ("last_listened", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lecture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_records",
                        to="lecture.lecture",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lecture_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "lecture"],
                        name="lecture_lec_user_id_5cffdd_idx",
                    ),
                    models.Index(
                        fields=["user", "completed"],
                        name="lecture_lec_user_id_b07901_idx",
                    ),
                ],
                "unique_together": {("user", "lecture")},
            },
        ),
    ]
