# Generated by Django 5.1.4 on 2025-08-29 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lecture", "0003_lectureprogress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lecture",
            name="duration",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
