# Generated by Django 5.1.4 on 2025-08-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lecture", "0003_alter_course_cover_alter_lecturer_photo"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="course",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="course",
            name="code",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="lecturer",
            name="code",
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="course",
            unique_together={("lecturer", "order", "code")},
        ),
    ]
