# Generated by Django 5.1.4 on 2025-08-31 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lecture", "0005_currentlecture"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FavoriteLecture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lecture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_by",
                        to="lecture.lecture",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_lectures",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="lecture_fav_user_id_fbe448_idx",
                    )
                ],
                "unique_together": {("user", "lecture")},
            },
        ),
        migrations.CreateModel(
            name="LectureHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("listened_at", models.DateTimeField(auto_now_add=True)),
                (
                    "duration_listened",
                    models.IntegerField(
                        default=0, help_text="Duration listened in seconds"
                    ),
                ),
                (
                    "completion_percentage",
                    models.FloatField(
                        default=0.0, help_text="Percentage of lecture completed"
                    ),
                ),
                (
                    "lecture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history_records",
                        to="lecture.lecture",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lecture_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "listened_at"],
                        name="lecture_lec_user_id_03b673_idx",
                    ),
                    models.Index(
                        fields=["user", "lecture"],
                        name="lecture_lec_user_id_a71208_idx",
                    ),
                ],
            },
        ),
    ]
