# Generated by Django 5.2.6 on 2025-09-17 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lecture", "0006_favoritelecture_lecturehistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecture",
            name="event",
            field=models.CharField(
                blank=True, help_text="Event or occasion of the lecture", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="lecture",
            name="year",
            field=models.PositiveIntegerField(
                blank=True, help_text="Year of the lecture", null=True
            ),
        ),
    ]
