# Generated by Django 5.2.6 on 2025-09-17 11:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lecture", "0007_lecture_event_lecture_year"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="lectureprogress",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name="lectureprogress",
            index=models.Index(
                fields=["updated_at"], name="lecture_lec_updated_4268a9_idx"
            ),
        ),
    ]
