# Generated by Django 5.2.6 on 2025-09-17 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lecture", "0008_lectureprogress_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lecturer",
            options={"ordering": ["level", "order", "name"]},
        ),
        migrations.AddField(
            model_name="lecturer",
            name="guru",
            field=models.ForeignKey(
                blank=True,
                help_text="Spiritual teacher (guru) of this lecturer",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="disciples",
                to="lecture.lecturer",
            ),
        ),
        migrations.AddField(
            model_name="lecturer",
            name="level",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Founder-Acharya"),
                    (2, "Direct Disciple"),
                    (3, "Grand Disciple"),
                ],
                default=2,
                help_text="Spiritual hierarchy level: 1=Founder-Acharya, 2=Direct Disciple, 3=Grand Disciple",
            ),
        ),
        migrations.AddIndex(
            model_name="lecturer",
            index=models.Index(
                fields=["level", "order"], name="lecture_lec_level_07ec18_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lecturer",
            index=models.Index(fields=["guru"], name="lecture_lec_guru_id_acdb6a_idx"),
        ),
    ]
